FROM node:18.16.1-bullseye-slim AS build-env
WORKDIR /sweater-comb
COPY ["package.json", "yarn.lock", "./"]
RUN yarn install
COPY . .
RUN yarn build

FROM node:18.16.1-bullseye-slim AS clean-env
COPY --from=build-env /sweater-comb/build/ /sweater-comb/
COPY --from=build-env /sweater-comb/babel.config.js /sweater-comb/
COPY --from=build-env /sweater-comb/package*.json /sweater-comb/
WORKDIR /sweater-comb
RUN yarn install --production

FROM --platform=amd64 gcr.io/snyk-main/ubuntu-20-node-18-basic:1.1.2_202306211040
ENV NODE_ENV production
COPY --from=clean-env /sweater-comb/ /sweater-comb/
WORKDIR /sweater-comb
USER snyk
ENTRYPOINT ["/nodejs/bin/node", "woollypully/index.js"]
