docker_build('gcr.io/snyk-main/sweater-comb-admissions', '.', dockerfile='Dockerfile')
k8s_yaml(
    helm('./helm',
        namespace='sweater-comb',
        values=[
            'helm/local/values.yaml',
            'helm/local/local.pki.yaml',
        ]))
