openapi: 3.0.3
x-optic-url: https://app.useoptic.com/organizations/orgid/apis/apiId
x-snyk-api-stability: experimental
info:
  title: v3
  version: 3.0.0
servers:
  - url: https://api.snyk.io/v3
    description: Public Snyk API
tags:
  - name: Thing
    description: Short description of what Thing represents
paths:
  /thing:
    x-snyk-resource-singleton: true
    get:
      summary: Singleton
      description: Get a thing
      operationId: getThing
      tags:
        - Thing
      parameters:
        - { $ref: "#/components/x-rest-common/parameters/Version" }
      responses:
        "200":
          description: Retrieved a thing successfully
          headers:
            snyk-version-requested:
              {
                $ref: "#/components/x-rest-common/headers/VersionRequestedResponseHeader",
              }
            snyk-version-served:
              {
                $ref: "#/components/x-rest-common/headers/VersionServedResponseHeader",
              }
            snyk-request-id:
              {
                $ref: "#/components/x-rest-common/headers/RequestIdResponseHeader",
              }
            snyk-version-lifecycle-stage:
              {
                $ref: "#/components/x-rest-common/headers/VersionStageResponseHeader",
              }
            deprecation:
              { $ref: "#/components/x-rest-common/headers/DeprecationHeader" }
            sunset: { $ref: "#/components/x-rest-common/headers/SunsetHeader" }
            location:
              { $ref: "#/components/x-rest-common/headers/LocationHeader" }
          content:
            application/vnd.api+json:
              schema: { $ref: "#/components/schemas/ThingResourceResponse" }
        "400": { $ref: "#/components/x-rest-common/responses/400" }
        "401": { $ref: "#/components/x-rest-common/responses/401" }
        "403": { $ref: "#/components/x-rest-common/responses/403" }
        "404": { $ref: "#/components/x-rest-common/responses/404" }
        "409": { $ref: "#/components/x-rest-common/responses/409" }
        "500": { $ref: "#/components/x-rest-common/responses/500" }
components:
  x-rest-common:
    $ref: "../../../../../components/common.yaml"
  schemas:
    ThingResourceResponse:
      type: object
      description: Response containing a single thing resource object
      properties:
        jsonapi: { $ref: "#/components/x-rest-common/schemas/JsonApi" }
        data: { $ref: "#/components/schemas/ThingResource" }
        links: { $ref: "#/components/x-rest-common/schemas/SelfLink" }

    ThingResource:
      type: object
      description: thing resource object
      properties:
        type: { $ref: "#/components/x-rest-common/schemas/Types" }
        attributes: { $ref: "#/components/schemas/ThingAttributes" }
        relationships: { $ref: "#/components/schemas/ThingRelationships" }
      additionalProperties: false

    ThingRelationships:
      type: object
      properties:
        example: { $ref: "#/components/x-rest-common/schemas/Relationship" }
      additionalProperties: false

    ThingAttributes:
      type: object
      properties:
        name:
          type: string
          description: Name of this instance of thing.
          example: thing
        created:
          type: string
          description: Timestamp when this instance of thing was created.
          format: date-time
          example: "2021-10-05T13:23:17Z"
        updated:
          type: string
          description: Timestamp when this instance of thing was last updated.
          format: date-time
          example: "2021-10-05T13:25:29Z"
        description:
          type: string
          description: User-friendly description of this instance of thing.
          example: "This is a thing named thing."
      additionalProperties: false
