apiVersion: v1
kind: Service
metadata:
  name: {{ include "sweater-comb-admissions.fullname" . }}
  labels:
    {{- include "sweater-comb-admissions.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "sweater-comb-admissions.selectorLabels" . | nindent 4 }}
