openapi: 3.0.3
x-snyk-api-stability: experimental
info:
  title: Repo Resource
  version: 3.0.0
  x-plural-name: repos
  x-singular-name: repo
servers:
  - url: /rest
    description: go-service-sample
tags:
  - name: Repo
    description: A repository
paths:
  /orgs/{orgId}/repos/{repoId}:
    get:
      summary: Get a repository
      description: Get a repository
      operationId: getRepo
      tags:
        - Repo
      x-cerberus:
        authorization:
          resource:
            pathId: 'orgId'
            type: 'org'
            entitlements:
              - api
            permissions:
              - read
      parameters:
        - $ref: '#/components/x-rest-common/parameters/Version'
        - $ref: '#/components/parameters/OrgId'
        - $ref: '#/components/parameters/RepoId'
      responses:
        '200':
          description: Returns a repository
          headers:
            snyk-version-requested:
              $ref: >-
                #/components/x-rest-common/headers/VersionRequestedResponseHeader
            snyk-version-served:
              $ref: '#/components/x-rest-common/headers/VersionServedResponseHeader'
            snyk-request-id:
              $ref: '#/components/x-rest-common/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/x-rest-common/headers/VersionStageResponseHeader'
            deprecation:
              $ref: '#/components/x-rest-common/headers/DeprecationHeader'
            sunset:
              $ref: '#/components/x-rest-common/headers/SunsetHeader'
          content:
            application/vnd.api+json:
              schema:
                properties:
                  jsonapi:
                    $ref: '#/components/x-rest-common/schemas/JsonApi'
                  data:
                    type: object
                    description: repo resource object
                    required:
                      - id
                      - type
                    properties:
                      id:
                        type: string
                        format: uuid
                        example: d5b640e5-d88c-4c17-9bf0-93597b7a1ce2
                      type:
                        $ref: '#/components/x-rest-common/schemas/Types'
                      attributes:
                        $ref: '#/components/schemas/RepoAttributes'
                      relationships:
                        $ref: '#/components/schemas/RepoRelationships'
                    additionalProperties: false
                  links:
                    $ref: '#/components/x-rest-common/schemas/PaginatedLinks'
        '400':
          $ref: '#/components/x-rest-common/responses/400'
        '401':
          $ref: '#/components/x-rest-common/responses/401'
        '403':
          $ref: '#/components/x-rest-common/responses/403'
        '404':
          $ref: '#/components/x-rest-common/responses/404'
        '409':
          $ref: '#/components/x-rest-common/responses/409'
        '500':
          $ref: '#/components/x-rest-common/responses/500'
    delete:
      summary: Delete a repository
      description: Delete a repository
      operationId: deleteRepo
      tags:
        - Repo
      x-cerberus:
        authorization:
          resource:
            pathId: 'orgId'
            type: 'org'
            entitlements:
              - api
            permissions:
              - delete
      parameters:
        - $ref: '#/components/x-rest-common/parameters/Version'
        - $ref: '#/components/parameters/OrgId'
        - $ref: '#/components/parameters/RepoId'
      responses:
        '204':
          $ref: '#/components/x-rest-common/responses/204'
        '400':
          $ref: '#/components/x-rest-common/responses/400'
        '401':
          $ref: '#/components/x-rest-common/responses/401'
        '403':
          $ref: '#/components/x-rest-common/responses/403'
        '404':
          $ref: '#/components/x-rest-common/responses/404'
        '409':
          $ref: '#/components/x-rest-common/responses/409'
        '500':
          $ref: '#/components/x-rest-common/responses/500'
  /orgs/{orgId}/repos:
    get:
      summary: List repositories
      description: List repositories
      operationId: listRepo
      tags:
        - Repo
      x-cerberus:
        authorization:
          resource:
            pathId: 'orgId'
            type: 'org'
            entitlements:
              - api
            permissions:
              - read
      parameters:
        - $ref: '#/components/x-rest-common/parameters/Version'
        - $ref: '#/components/parameters/OrgId'
        - $ref: '#/components/x-rest-common/parameters/StartingAfter'
        - $ref: '#/components/x-rest-common/parameters/EndingBefore'
        - $ref: '#/components/x-rest-common/parameters/Limit'
      responses:
        '200':
          description: Returns a list of repositories
          headers:
            snyk-version-requested:
              $ref: >-
                #/components/x-rest-common/headers/VersionRequestedResponseHeader
            snyk-version-served:
              $ref: '#/components/x-rest-common/headers/VersionServedResponseHeader'
            snyk-request-id:
              $ref: '#/components/x-rest-common/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/x-rest-common/headers/VersionStageResponseHeader'
            deprecation:
              $ref: '#/components/x-rest-common/headers/DeprecationHeader'
            sunset:
              $ref: '#/components/x-rest-common/headers/SunsetHeader'
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  jsonapi:
                    $ref: '#/components/x-rest-common/schemas/JsonApi'
                  data:
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - type
                      properties:
                        id:
                          type: string
                          format: uuid
                          example: d5b640e5-d88c-4c17-9bf0-93597b7a1ce2
                        type:
                          $ref: '#/components/x-rest-common/schemas/Types'
                        attributes:
                          $ref: '#/components/schemas/RepoAttributes'
                        relationships:
                          $ref: '#/components/schemas/RepoRelationships'
                  links:
                    $ref: '#/components/x-rest-common/schemas/PaginatedLinks'
        '400':
          $ref: '#/components/x-rest-common/responses/400'
        '401':
          $ref: '#/components/x-rest-common/responses/401'
        '403':
          $ref: '#/components/x-rest-common/responses/403'
        '404':
          $ref: '#/components/x-rest-common/responses/404'
        '409':
          $ref: '#/components/x-rest-common/responses/409'
        '500':
          $ref: '#/components/x-rest-common/responses/500'
    post:
      summary: Create a new repository
      description: Create a new repository
      operationId: createRepo
      tags:
        - Repo
      x-cerberus:
        authorization:
          resource:
            pathId: 'orgId'
            type: 'org'
            entitlements:
              - api
            permissions:
              - create
      parameters:
        - $ref: '#/components/x-rest-common/parameters/Version'
        - $ref: '#/components/parameters/OrgId'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - type
              properties:
                type:
                  type: string
                attributes:
                  $ref: '#/components/schemas/RepoCreateAttributes'
              additionalProperties: false
      responses:
        '201':
          description: Created repository successfully
          headers:
            snyk-version-requested:
              $ref: >-
                #/components/x-rest-common/headers/VersionRequestedResponseHeader
            snyk-version-served:
              $ref: '#/components/x-rest-common/headers/VersionServedResponseHeader'
            snyk-request-id:
              $ref: '#/components/x-rest-common/headers/RequestIdResponseHeader'
            snyk-version-lifecycle-stage:
              $ref: '#/components/x-rest-common/headers/VersionStageResponseHeader'
            deprecation:
              $ref: '#/components/x-rest-common/headers/DeprecationHeader'
            sunset:
              $ref: '#/components/x-rest-common/headers/SunsetHeader'
            location:
              $ref: '#/components/x-rest-common/headers/LocationHeader'
          content:
            application/vnd.api+json:
              schema:
                properties:
                  jsonapi:
                    $ref: '#/components/x-rest-common/schemas/JsonApi'
                  data:
                    type: object
                    description: repo resource object
                    required:
                      - id
                      - type
                    properties:
                      id:
                        type: string
                        format: uuid
                        example: d5b640e5-d88c-4c17-9bf0-93597b7a1ce2
                      type:
                        $ref: '#/components/x-rest-common/schemas/Types'
                      attributes:
                        $ref: '#/components/schemas/RepoAttributes'
                      relationships:
                        $ref: '#/components/schemas/RepoRelationships'
                    additionalProperties: false
                  links:
                    $ref: '#/components/x-rest-common/schemas/PaginatedLinks'
        '400':
          $ref: '#/components/x-rest-common/responses/400'
        '401':
          $ref: '#/components/x-rest-common/responses/401'
        '403':
          $ref: '#/components/x-rest-common/responses/403'
        '404':
          $ref: '#/components/x-rest-common/responses/404'
        '409':
          $ref: '#/components/x-rest-common/responses/409'
        '500':
          $ref: '#/components/x-rest-common/responses/500'
components:
  schemas:
    RepoAttributes:
      type: object
      properties:
        created:
          type: string
          format: date-time
        name:
          type: string
        link:
          type: string
          format: uri
        type:
          type: string
          enum:
            - private
            - public
      required:
        - name
        - type
      example:
        created: '2022-01-14T00:23:50Z'
        name: Snyk
        link: https://app.snyk.io
        type: private
    RepoRelationships:
      type: object
      properties: {}
      additionalProperties: false
    RepoCreateAttributes:
      type: object
      properties:
        name:
          type: string
        link:
          type: string
          format: uri
        type:
          type: string
          enum:
            - private
            - public
      required:
        - name
        - type
      example:
        created: '2022-01-14T00:23:50Z'
        name: Snyk
        link: https://app.snyk.io
        type: private
  x-rest-common:
    $ref: >-
      https://raw.githubusercontent.com/snyk/sweater-comb/common-model-v1/components/common.yaml
  parameters:
    RepoId:
      name: repoId
      in: path
      required: true
      description: Repository identifier
      schema:
        type: string
        format: uuid
    OrgId:
      name: orgId
      in: path
      required: true
      description: Organization identifier
      schema:
        type: string
        format: uuid
